branch-defaults:
  default:
    environment: mrb-backend-env
    group_suffix: null
  release-1.0:
    environment: mrb-backend-env
environment-defaults:
  mrb-backend-env:
    branch: release-1.0
    repository: null
global:
  application_name: mrb-backend
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: sa-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
