"""create table exam_file

Revision ID: 69f4756bcae3
Revises: 7b09d1ebb41e
Create Date: 2020-05-21 01:49:22.374592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '69f4756bcae3'
down_revision = '7b09d1ebb41e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_files',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('exam_id', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_files')
    # ### end Alembic commands ###

